'use client'

export type {
  RecordType,
  ClassRecord,
  ResourceType,
  ClassResource,
  DataCache,
} from './store/cache'

export {
  getCache,
  isCacheLoaded,
  isCacheLoading,
  triggerSync,
  loadAllDataFromAPI,
  debouncedSyncStore,
  generateId,
} from './store/cache'

export {
  getClasses,
  saveClassAsync,
  updateClassAsync,
  deleteClassAsync,
  saveClass,
  updateClass,
  deleteClass,
  syncClassToTeachers,
  getClassTypeLabel,
  getClassTypeColor,
  getCustomClassTypes,
  addCustomClassType,
  getAllClassTypeOptions,
} from './store/classes'

export type { StudentSortBy } from './store/students'
export {
  getStudentSortBy,
  setStudentSortBy,
  getStudentCustomOrder,
  setStudentCustomOrder,
  sortStudents,
  getStudents,
  getStudentsByClass,
  saveStudentAsync,
  saveStudent,
  updateStudent,
  addStudentToClass,
  deleteStudent,
} from './store/students'

export {
  getRecordsByClass,
  saveRecord,
  deleteRecord,
  getRecordTypeLabel,
  getRecordTypeIcon,
  getResourcesByClass,
  saveResource,
  deleteResource,
  updateResource,
  getResourceTypeLabel,
  getResourceTypeIcon,
} from './store/records'

export {
  getBoundTeachers,
  getSelectedTeacherId,
  setSelectedTeacherId,
  getAllClasses,
  getClassSchedules,
  saveClassScheduleAsync,
  saveClassSchedule,
  updateClassSchedule,
  deleteClassSchedule,
  getCurrentClassByTime,
  getTodayClasses,
  getMarkedDays,
  setMarkedDay,
  isMarkedDay,
  isScheduleDayForClass,
  getDeletedScheduleDates,
  addDeletedScheduleDate,
  removeDeletedScheduleDate,
} from './store/schedules'

export {
  getCourseTasks,
  getCourseTasksByClass,
  getCourseTasksByDate,
  saveCourseTask,
  updateCourseTask,
  deleteCourseTask,
  getTodayTaskStats,
  getCourseTaskTemplates,
  getCourseTaskTemplatesByClass,
  saveCourseTaskTemplate,
  updateCourseTaskTemplate,
  deleteCourseTaskTemplate,
  initializeLessonProgress,
  getLessonForClassDate,
  updateLessonProgress,
  getCourseTasksByClassAndDate,
  generateDailyInstances,
  ensureTodayInstancesForAllClasses,
  syncTemplateToFutureInstances,
} from './store/course-tasks'

export {
  getHomeworkAssessments,
  getHomeworkAssessmentsByStudent,
  getHomeworkAssessmentsByClass,
  saveHomeworkAssessment,
  updateHomeworkAssessment,
  deleteHomeworkAssessment,
  getQuizRecords,
  getQuizRecordsByStudent,
  getQuizRecordsByClass,
  saveQuizRecord,
  updateQuizRecord,
  deleteQuizRecord,
  getAllOverallAccuracyRecords,
  getClassOverallAccuracyRecords,
  computeAndSaveClassAccuracy,
} from './store/assessments'

export {
  getFeedbackHistory,
  getFeedbackHistoryByStudent,
  saveFeedbackHistory,
  deleteFeedbackHistory,
  clearFeedbackHistory,
  getNotifications,
  getUnreadNotifications,
  getActiveNotifications,
  addNotification,
  markNotificationRead,
  markNotificationCompleted,
  dismissNotification,
  dismissAllActiveNotifications,
  markNotificationsCompletedByClass,
  getPushLogs,
  addPushLog,
  getTodayPushLogs,
  getRemindersSent,
  hasReminderBeenSent,
  markReminderSent,
  clearExpiredReminderRecords,
  getObservationRecords,
  saveObservationRecord,
  deleteObservationRecord,
} from './store/feedback'
